export const homeAssets = {
  figmaIcon: "/assets/images/home/figma-icon.svg",
  githubIcon: "/assets/images/home/github-icon.svg",
  linkedinIcon: "/assets/images/home/linkedin-icon.svg",
  heroPattern: "/assets/images/home/hero-pattern.svg",
  heroPatternMobile: "/assets/images/home/hero-pattern-mobile.svg",
  heroPatternDark: "/assets/images/home/hero-pattern-dark.svg",
  heroPatternDarkMobile: "/assets/images/home/mobile-hero-section-dark.svg",
  patrickLight: "/assets/images/home/patrick-light.png",
  patrickDark: "/assets/images/home/patrick-dark.png",
  peacePatrick: "/assets/images/home/peace-patrick.png",
  peacePatrickMobile: "/assets/images/home/peace-patrick-mobile.png",
  accessibilityBlackIcon: "/assets/images/home/accessibility-black.png",
  accessibilityWhiteIcon: "/assets/images/home/accessibility-white.png",
};

export const sharedAssets = {
  buttonArrow: "/assets/images/pages/button-arrow.svg",
  buttonArrowDark: "/assets/images/pages/button-arrow-dark.svg",
};

export const deviceAssets = {
  devices: {
    laptop: "/assets/images/pages/devices/laptop.png",
    ipad: "/assets/images/pages/devices/ipad.png",
    iphone: "/assets/images/pages/devices/iphone.png",
    mmc: "/assets/images/pages/devices/mmc.png",
    appleDisplay: "/assets/images/pages/devices/apple-display.png",
  },
};

export const bishopAssets = {
  logo: "/assets/images/bishop/bishop-logo.png",
  logoDark: "/assets/images/bishop/bishop-logo-dark.png",
  team: {
    patrick: "/assets/images/bishop/Paddy.png",
    shelby: "/assets/images/bishop/Shelbs.png",
  },
  sparkle: "/assets/images/bishop/vision-sparkle.png",
  sparkleLeft: "/assets/images/bishop/sparkle-left.png",
  sparkleRight: "/assets/images/bishop/sparkle-right.png",
  bubbles: [
    "/assets/images/bishop/vision-bubble-1.png",
    "/assets/images/bishop/vision-bubble-2.png",
    "/assets/images/bishop/vision-bubble-3.png",
    "/assets/images/bishop/vision-bubble-4.png",
    "/assets/images/bishop/vision-bubble-5.png",
  ],
  personas: [
    "/assets/images/bishop/persona-kyle.png",
    "/assets/images/bishop/persona-mandy.png",
    "/assets/images/bishop/persona-tyler.png",
  ],
  concepts: [
    "/assets/images/bishop/concepts_1.png",
    "/assets/images/bishop/concepts_2.png",
    "/assets/images/bishop/concepts_3.png",
    "/assets/images/bishop/concepts_4.png",
    "/assets/images/bishop/concepts_5.png",
    "/assets/images/bishop/concepts_6.png",
    "/assets/images/bishop/concepts_7.png",
    "/assets/images/bishop/concepts_8.png",
  ],
  researchPapers: [
    "/assets/images/bishop/research_paper_1.png",
    "/assets/images/bishop/research_paper_2.png",
    "/assets/images/bishop/research_paper_3.png",
    "/assets/images/bishop/research_paper_4.png",
    "/assets/images/bishop/research_paper_5.png",
    "/assets/images/bishop/research_paper_6.png",
    "/assets/images/bishop/research_paper_7.png",
  ],
  magnifyingGlass: "/assets/images/bishop/magnifying_glass.png",
  magnifyingGlassDark: "/assets/images/bishop/magnifying_glass-dark.png",
  annotateImage: "/assets/images/bishop/annotate_image.png",
  annotateVideo: "/assets/images/bishop/annotate.mp4",
  annotateMobileImage: "/assets/images/bishop/mobile_annotate.png",
  annotateMobileVideo: "/assets/images/bishop/mobile_annotate.mp4",
  trainModel: "/assets/images/bishop/ml_train.png",
  inferenceFrames: [
    "/assets/images/bishop/inference_1.png",
    "/assets/images/bishop/inference_2.png",
    "/assets/images/bishop/inference_3.png",
    "/assets/images/bishop/inference_4.png",
    "/assets/images/bishop/inference_5.png",
    "/assets/images/bishop/inference_6.png",
    "/assets/images/bishop/inference_7.png",
  ],
  trackerV1: "/assets/images/bishop/v1_tracker.mp4",
  trackerV4: "/assets/images/bishop/v4_tracker.mp4",
  clientVideo: "/assets/images/bishop/client_video.mp4",
  iterationThreeDesktop: "/assets/images/bishop/desktop_iteration_3.png",
  iterationThreeMobile: "/assets/images/bishop/mobile_iteration_3.png",
  aiDetections: "/assets/images/bishop/ai_detections.mp4",
  manageVideosDesktop: "/assets/images/bishop/desktop_manage_video.png",
  manageVideosMobile: "/assets/images/bishop/mobile_manage_video.png",
  mapDemo: "/assets/images/bishop/map_demo.mp4",
};
